jobs:

- template: _build/azure-pipelines-template.yml
  parameters:
    name: Linux
    target: x86_64-unknown-linux-gnu
    vmImage: ubuntu-16.04

- template: _build/azure-pipelines-template.yml
  parameters:
    name: Android
    target: aarch64-linux-android
    vmImage: ubuntu-16.04

- template: _build/azure-pipelines-template.yml
  parameters:
    name: macOS
    target: x86_64-apple-darwin
    vmImage: macOS-10.13

- template: _build/azure-pipelines-template.yml
  parameters:
    name: iOS
    target: "aarch64-apple-ios x86_64-apple-ios armv7-apple-ios armv7s-apple-ios"
    vmImage: macOS-10.13

- template: _build/azure-pipelines-template.yml
  parameters:
    name: Windows
    target: x86_64-pc-windows-msvc
    vmImage: vs2017-win2016

- job: release
  steps:
  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
      githubConnection: rpgp-release
      repositoryName: rpgp/rpgp
      tagSource: manual
      tag: $(Build.SourceVersion)
      assets: |
        $(Build.ArtifactStagingDirectory)/**
