jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      nightly:
        rustup_toolchain: nightly
  steps:
  - ${{ if ne(parameters.name, 'Windows') }}:
    # Linux and macOS.
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
  - ${{ if startsWith(parameters.name, 'Windows') }}:
    # Windows.
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      displayName: Install rust (windows)
  # All platforms.
  - script: |
        rustc -Vv
        cargo -V
    displayName: Query rust and cargo versions
  - ${{ if ne(parameters.name, 'Windows') }}:
    - script: ci/build.sh
      env:
        TARGET: ${{ parameters.target }}
      displayName: Build
  - ${{ if eq(parameters.name, 'Windows') }}:
    - script: ci\build.sh
      env:
        TARGET: ${{ parameters.target }}
      displayName: Build
  - task: CopyFiles@2
    inputs:
      contents: 'librpgp*'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: "librpgp-$(Build.SourceVersion)-${{ parameters.target }}"
  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
      githubConnection: rpgp-bot
      repositoryName: rpgp/rpgp
      tagSource: manual
      tag: $(Build.SourceVersion)
      assets: |
        $(Build.ArtifactStagingDirectory)/**
